colleen: 
	gcc -Wall -Wextra -Werror Colleen.c -o Colleen
	./Colleen

grace: 
	gcc -Wall -Wextra -Werror Grace.c -o Grace
	./Grace

colleen: 
	gcc -Wall -Wextra -Werror Sully.c -o Sully
	./Sully

clean:
	@rm Colleen 2>/dev/null || echo "Unexisting Colleen"
	@rm Grace 2>/dev/null || echo "Unexisting Grace"
	@rm Sully 2>/dev/null || echo "Unexisting Sully"